name: 🚀 Deploy Laravel to cPanel

on:
  push:
    branches:
      - main   # déploie seulement quand on push sur la branche main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code source
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Déploiement FTP
      - name: 📂 Deploy to cPanel via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
            server: ${{ secrets.FTP_SERVER }}
            username: ${{ secrets.FTP_USERNAME }}
            password: ${{ secrets.FTP_PASSWORD }}
            protocol: ftps
            port: 21
            security: loose
            server-dir: /public_html/
            local-dir: ./
            dangerous-clean-slate: false

