name: 🚀 Deploy Laravel to cPanel

on:
  push:
    branches:
      - main   # déploie seulement quand on push sur la branche main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code source
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Déploiement FTP
      - name: 📂 Deploy to cPanel via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}      # ex: ftp://ftp.mondomaine.com
          username: ${{ secrets.FTP_USERNAME }}  # ton login FTP
          password: ${{ secrets.FTP_PASSWORD }}  # ton mot de passe FTP
          protocol: ftps                         # ftp ou ftps selon ton hébergeur
          local-dir: ./                          # dossier local à uploader
          server-dir: /public_html/              # répertoire distant sur cPanel
          dangerous-clean-slate: true            # supprime les anciens fichiers avant upload (⚠️)
